export interface Review {
  author: string;
  text: string;
}

export interface ContentBlock {
  type: 'para' | 'list' | 'heading' | 'highlight' | 'reviews' | 'sublist';
  icon?: string;
  heading?: string;
  text?: string;
  items?: string[];
  reviews?: Review[];
  sublists?: { title: string; items: string[] }[];
}

export interface DoctorDetail {
  id: number;
  slug: string;
  image: string;
  name: string;
  qualification: string;
  specialty: string;
  tagline: string;
  phone: string;
  email: string;
  location: string;
  accent: string;
  accentBorder: string;
  badge: string;
  title: string;
  experience?: string;
  procedures?: string;
  content: ContentBlock[];
  hasCommentForm?: boolean;
}

export const doctorsData: DoctorDetail[] = [
  {
    id: 1,
    slug: 'dr-binidra-banerjee-leading-gastroenterologist-in-asansol-durgapur-dhanbad-and-jharkhand',
    image: '/d.png',
    name: 'Dr. Binidra Banerjee',
    qualification: 'MBBS, Fellowship (Therapeutic Endoscopy & Diabetology)',
    specialty: 'Senior Consultant Gastroenterologist',
    tagline: 'Leading Gastroenterologist in Asansol, Durgapur, Dhanbad, and Jharkhand',
    phone: '07364921002',
    email: 'acharjeehealth.in@gmail.com',
    location: 'ACHARJEE PHARMACY, MORE C/O, 256/2, SB Gorai Rd, Ismile, Islampur, Hamid Nagar, Asansol, West Bengal 713301',
    accent: '#fce4ec',
    accentBorder: '#e91e63',
    badge: 'Gastro',
    title: 'Meet our best Senior Consultant Gastroenterologist',
    experience: '10+ Years',
    procedures: '50,000+',
    content: [
      {
        type: 'para',
        text: 'Acharjee Health Clinic takes pride in being associated with Dr. Binidra Banerjee, a distinguished and highly experienced Gastroenterologist, delivering best-in-class medical gastroenterology and endoscopy services across Asansol, Raniganj, Durgapur, Chittaranjan, Madhupur, Dumka, Dhanbad, Purulia, and Jharkhand.',
      },
      {
        type: 'para',
        text: 'Dr. Binidra Banerjee completed his MBBS from Rajiv Gandhi University of Health Sciences, followed by his Post-Graduation from South Eastern Railway Hospital, Kolkata. He pursued a Fellowship in Therapeutic Endoscopy from BGS Gleneagles Hospital, Bengaluru, and a Fellowship in Diabetology from Apollo Gleneagles Hospital, Kolkata.',
      },
      {
        type: 'para',
        text: 'In 2017, Dr. Binidra Banerjee joined IQ City Medical College, Durgapur, as an Assistant Professor and Endoscopist in the Department of Medical Gastroenterology. At present, he is attached to multiple reputed hospitals in Durgapur, Suiri (Birbhum), Bankura, and Asansol. With a remarkable track record of approximately 50,000 endoscopic and colonoscopic procedures, Dr. Banerjee exemplifies operational efficiency, clinical precision, and patient-centric care.',
      },
      {
        type: 'heading',
        icon: '🎓',
        heading: 'Educational Background',
        items: [
          'MBBS – Rajiv Gandhi University of Health Sciences',
          'Post-Graduation – South Eastern Railway Hospital, Kolkata',
          'Fellowship in Therapeutic Endoscopy – BGS Gleneagles Hospital, Bengaluru',
          'Fellowship in Diabetology – Apollo Gleneagles Hospital, Kolkata',
        ],
      },
      {
        type: 'heading',
        icon: '🏥',
        heading: 'Conditions Treated',
        items: [
          'Gastritis', 'Acidity and Acid Peptic Disease', 'Gastric and Duodenal Ulcers',
          'Abdominal Pain', 'Pancreatitis', 'Fatty Liver Disease',
          'Hepatitis and Liver Disorders', 'Colitis and Inflammatory Bowel Disease',
          'Chronic Constipation', 'Piles and Hemorrhoids',
          'Jaundice and Liver Dysfunction', 'Gastrointestinal (GI) Bleeding',
        ],
      },
      {
        type: 'heading',
        icon: '🏆',
        heading: 'Professional Memberships',
        items: [
          'American College of Gastroenterology (ACG)',
          'Indian Society of Gastroenterology (ISG)',
          'Society of Endoscopic Gastroenterology of India (SEGI)',
          'Other national and international medical bodies',
        ],
      },
      {
        type: 'heading',
        icon: '✅',
        heading: 'Why Choose Dr. Binidra Banerjee at Acharjee Health Clinic?',
        items: [
          'Advanced diagnostic and therapeutic endoscopy',
          'Evidence-based gastroenterology treatment',
          'Patient-centric, result-driven clinical approach',
          'Multidisciplinary care integration',
          'Academic excellence and research-backed treatment protocols',
        ],
      },
    ],
  },
  {
    id: 2,
    slug: 'dr-atri-bandyopadhyay-doctor-in-asansol',
    image: '/d1.png',
    name: 'Dr. Atri Bandyopadhyay',
    qualification: 'MBBS, MS (ENT)',
    specialty: 'Senior ENT Specialist & Head Neck Surgeon',
    tagline: 'Best Senior ENT Specialist in Asansol, West Bengal | Acharjee Health',
    phone: '073649 21002',
    email: 'acharjeehealth.in@gmail.com',
    location: 'ACHARJEE PHARMACY, MORE C/O, 256/2, SB Gorai Road, Ismile, Islampur, Pathak Bari, Asansol, West Bengal – 713301',
    accent: '#e0f7fa',
    accentBorder: '#00acc1',
    badge: 'ENT',
    title: 'Meet our best Senior ENT Specialist and Head Neck Surgeon',
    experience: '30+ Years',
    content: [
      {
        type: 'para',
        text: 'Dr. Atri Bandyopadhyay, MBBS, MS (ENT), is known for procedures like cochlear implants, but his primary association is with Manipal Hospital (Mukundapur), with over 30 years in ENT. He is currently available for consultation at Acharjee Health Clinic and Pharmacy, located in Asansol, West Bengal.',
      },
      {
        type: 'heading',
        icon: '🎓',
        heading: 'Educational Background',
        items: [
          'MBBS – Nilratan Sircar Medical College, Calcutta University',
          'MS in ENT – JN Medical College, Aligarh Muslim University, Aligarh',
        ],
      },
      {
        type: 'heading',
        icon: '💼',
        heading: 'Clinical Experience',
        items: [
          'Asst Professor ENT: Sikkim Manipal University',
          'Visiting Consultant ENT Surgeon: Rabindranath Tagore Institute of Cardiac Science, Mukundapur, Kolkata',
          'Practicing as Consultant ENT Surgeon from 2002',
        ],
      },
      {
        type: 'heading',
        icon: '🔬',
        heading: 'ENT & Facial Plastic Surgery Expertise',
        items: [
          'Endoscopic ear and nose surgeries',
          'Facial plastic & reconstructive surgery',
          'Skull base and maxillofacial trauma procedures',
          'Cochlear implant surgeries under ADIP scheme',
          'Functional and cosmetic rhinoplasty',
          'Mastoid and temporal bone surgeries',
        ],
      },
      {
        type: 'heading',
        icon: '📖',
        heading: 'Medical Research & Publications',
        items: [
          'Published in national and peer-reviewed journals on common and complex ENT conditions',
          'Research on Cochlear Implantation, Septoplasty, and management of chronic Sinusitis',
          'Integration of Balloon Sinuplasty and Functional Endoscopic Sinus Surgery (FESS)',
        ],
      },
      {
        type: 'heading',
        icon: '✅',
        heading: 'Why Choose Dr. Atri Bandyopadhyay?',
        items: [
          'Compassionate and patient-first approach',
          'Precision in microsurgeries and advanced ENT procedures',
          'Affordable consultation at a trusted local clinic',
        ],
      },
    ],
  },
  {
    id: 3,
    slug: 'dr-rupam-sil-ent-specialist-in-asansol-west-bengal',
    image: '/d2.png',
    name: 'Dr. Rupam Sil',
    qualification: 'MBBS, DLO, MS (Anatomy)',
    specialty: 'ENT Specialist & Head Neck Surgeon',
    tagline: 'Best ENT Specialist in Asansol, West Bengal | Acharjee Health',
    phone: '073649 21002',
    email: 'acharjeehealth.in@gmail.com',
    location: 'ACHARJEE PHARMACY, MORE C/O, 256/2, SB Gorai Road, Ismile, Islampur, Pathak Bari, Asansol, West Bengal – 713301',
    accent: '#fff8e1',
    accentBorder: '#f9a825',
    badge: 'ENT',
    title: 'Meet our best ENT Specialist and Head Neck Surgeon',
    experience: '30+ Years',
    content: [
      {
        type: 'para',
        text: 'Dr. Rupam Sil, MBBS, DLO, MS (Anatomy) is a highly regarded Consultant ENT Surgeon based in Kolkata, with nearly three decades of experience in the field of Otorhinolaryngology. He is currently affiliated with Fortis Hospital, Anandapur, and is available for consultation at Acharjee Health Clinic and Pharmacy, Asansol, West Bengal.',
      },
      {
        type: 'heading',
        icon: '🎓',
        heading: 'Educational Background',
        items: [
          'MBBS – University of Calcutta (1997)',
          'DLO (Diploma in Otorhinolaryngology) – University of Calcutta (2000)',
          'MS (Master of Surgery) – University of Calcutta (2003)',
        ],
      },
      {
        type: 'heading',
        icon: '💼',
        heading: 'Clinical Experience',
        items: [
          'Fortis Hospital, Anandapur: Serving as a Consultant ENT Specialist',
          'NH Rabindranath Tagore RTIICS: Visiting Consultant',
          'Apollo Clinic, Lake Gardens: Consultant ENT Surgeon',
          'Past: Medica Superspecialty Hospital, Hindusthan Health Point, Woodlands Multispeciality Hospital',
        ],
      },
      {
        type: 'heading',
        icon: '🔬',
        heading: 'ENT & Surgical Expertise',
        items: [
          'Otology (Ear Surgery) – Micro ear surgeries',
          'Rhinology (Nasal Surgery) – Advanced FESS',
          'Laser & Coblator Assisted Surgery',
          'Laryngology – Micro laryngeal surgeries for voice/throat disorders',
          'Cochlear Implants – Evaluation and surgical management',
          'Sleep Surgery – Surgical interventions for sleep apnea and snoring',
        ],
      },
      {
        type: 'heading',
        icon: '✅',
        heading: 'Why Choose Dr. Rupam Sil?',
        items: [
          'Compassionate and patient-first approach',
          'Precision in microsurgeries and advanced ENT procedures',
          'Affordable consultation at a trusted local clinic',
        ],
      },
    ],
  },
  {
    id: 4,
    slug: 'best-neurologist-in-asansol-2',
    image: '/d3.png',
    name: 'Dr. Ananth Egoor',
    qualification: 'MBBS, MS (General Surgery), M.Ch (Neurosurgery – NIMS Hyderabad)',
    specialty: 'Senior Consultant Neurosurgeon',
    tagline: 'Best Neurologist Consultant in Asansol – Dr. Ananth Egoor (From Hyderabad)',
    phone: '073649 21002',
    email: 'acharjeehealth.in@gmail.com',
    location: 'ACHARJEE PHARMACY, MORE C/O, 256/2, SB Gorai Road, Ismile, Islampur, Pathak Bari, Asansol, West Bengal – 713301',
    accent: '#fce4ec',
    accentBorder: '#e53935',
    badge: 'Neuro',
    title: 'Meet our best Senior Consultant Neurosurgeon',
    experience: '12+ Years',
    procedures: '2000+',
    content: [
      {
        type: 'para',
        text: 'Dr. Ananth Egoor, MBBS, MS (General Surgery), M.Ch (Neurosurgery – NIMS Hyderabad), is a renowned Senior Consultant Neurosurgeon at Omega Hospitals, Hyderabad, with 12+ years expertise in brain and spine surgery and over 2000 procedures. He was awarded the Gold Medal for academic and clinical excellence. His approach combines cutting-edge technology with a patient-first philosophy.',
      },
      {
        type: 'heading',
        icon: '🎓',
        heading: 'Educational Background',
        items: [
          'MBBS – SVS Medical College, Mahbubnagar (Topper in Anatomy)',
          'MS in General Surgery – Osmania Medical College, Hyderabad',
          'MCh in Neurosurgery – Nizam\'s Institute of Medical Sciences (NIMS), Hyderabad (Gold Medalist)',
        ],
      },
      {
        type: 'heading',
        icon: '💼',
        heading: 'Clinical Experience',
        items: [
          'Senior Consultant Neurosurgeon at Omega Hospitals, Hyderabad',
          'Consultant Neurosurgeon at Yashoda Hospitals',
          'Former Consultant at TX Hospitals and Citi Neuro Centre',
          'Former Senior Resident Neurosurgeon at Osmania General Hospital',
        ],
      },
      {
        type: 'heading',
        icon: '🔬',
        heading: 'Neurosurgery Expertise',
        items: [
          'Precision Brain Tumor Surgery',
          'Minimally Invasive Spine Surgery (MISS)',
          'Neurovascular Interventions',
          'Advanced Endoscopic Procedures',
          'Complex Spinal Reconstruction',
          'Comprehensive Neuro-Trauma Care',
        ],
      },
      {
        type: 'heading',
        icon: '🏆',
        heading: 'Awards & Recognition',
        items: [
          '🥇 Gold Medalist in Neurosurgery (NIMS, Hyderabad)',
          '🏅 Topper in Anatomy during MBBS tenure',
          '🏆 Recognized as leading expert in Endoscopic and Keyhole Neurosurgery',
          '🎤 Published researcher in international medical journals',
        ],
      },
      {
        type: 'heading',
        icon: '✅',
        heading: 'Why Choose Dr. Ananth Egoor?',
        items: [
          'Compassionate and patient-first approach',
          'Academic excellence and gold-medal achievements',
          'Affordable consultation at a trusted local clinic',
        ],
      },
    ],
  },
  {
    id: 5,
    slug: 'top-dermatologist-in-asansol-kolkata',
    image: '/d4.png',
    name: 'Dr. Shibasis Chatterjee',
    qualification: 'MBBS, MD (Dermatology, Venereology & Leprosy)',
    specialty: 'Consultant Dermatologist',
    tagline: 'The Best Skin Specialist in Asansol, West Bengal | Acharjee Health',
    phone: '07364921002 / 7029386969',
    email: 'acharjeehealth.in@gmail.com',
    location: 'ACHARJEE PHARMACY, MORE C/O, 256/2, SB Gorai Rd, Ismile, Islampur, Hamid Nagar, Asansol, West Bengal 713301',
    accent: '#e8f5e9',
    accentBorder: '#43a047',
    badge: 'Derma',
    title: 'Know Your Dermatologist – Meet Dr. Shibasis Chatterjee',
    content: [
      {
        type: 'para',
        text: 'Dr. Shibasis Chatterjee is a renowned dermatologist in Asansol, West Bengal, known for his expertise, compassionate care, and modern skin care treatments. His MBBS and MD in Dermatology, Venereology, and Leprosy make him highly qualified. Patients appreciate his personalized treatment approach and advanced skin solutions.',
      },
      {
        type: 'heading',
        icon: '🎓',
        heading: 'Educational Qualifications',
        items: [
          'MBBS – Extensive medical training in general medicine',
          'MD (Dermatology, Venereology & Leprosy) – Specialist in skin, hair, and nail disorders',
        ],
      },
      {
        type: 'heading',
        icon: '🔬',
        heading: 'Skin-Friendly Services Offered',
        items: [
          'Acne & Pimple Treatment – Advanced acne care with scar reduction techniques',
          'Milia & Mole Removal – Safe, precise procedures with minimal discomfort',
          'Chemical Peels & Microdermabrasion – Skin rejuvenation for even tone and glow',
          'Radiofrequency Surgery & IPL Treatment – Non-invasive for pigmentation and skin tightening',
          'PRP for Hair Loss & Mesotherapy – Natural hair regeneration and scalp health',
        ],
      },
      {
        type: 'heading',
        icon: '⭐',
        heading: 'Patient Reviews',
        reviews: [
          { author: 'Kausin Mitra', text: '"One of The Best Dermatologists in the state. Dr Chatterjee is kind, caring, extremely knowledgeable, friendly and a patient listener. I\'ve had a chronic acne problem cured by him in only 2 months. Great to have such a great dermatologist in Asansol."' },
          { author: 'Chadalavada Pragathi', text: '"One of the best dermats in town for skin and hair problems. Doctor is very polite and patient friendly. I went for hair fall and had good results. Highly recommend Dr. Shibashis."' },
          { author: 'Vikram Mishra', text: '"I had a bad experience with hair fall. Dr Shibashis treated me and I got results (hair gain). He is also a nice and good person. Thanks Dr Shibashis."' },
        ],
      },
    ],
  },
  {
    id: 6,
    slug: 'gastroenterologist-in-asansol-kolkata',
    image: '/d5.png',
    name: 'Dr. Raghuram Tangirala',
    qualification: 'MBBS, MD (Internal Medicine), DM (Gastroenterology)',
    specialty: 'Gastroenterologist',
    tagline: 'Gastroenterologist in Asansol (from Hyderabad)',
    phone: '07364921002 / 7029386969',
    email: 'acharjeehealth.in@gmail.com',
    location: 'ACHARJEE PHARMACY, MORE C/O, 256/2, SB Gorai Rd, Ismile, Islampur, Hamid Nagar, Asansol, West Bengal 713301',
    accent: '#e8f0fe',
    accentBorder: '#3f51b5',
    badge: 'Gastro',
    title: 'Dr. Raghuram Tangirala – Gastroenterologist in Asansol (from Hyderabad)',
    content: [
      {
        type: 'para',
        text: 'Dr. Raghuram Tangirala brings advanced specialty training and clinical experience from Hyderabad to Asansol, West Bengal. He is a medically trained specialist in Gastroenterology with a foundation in Internal Medicine, enabling evaluation of symptoms that may overlap across multiple systems.',
      },
      {
        type: 'heading',
        icon: '🎓',
        heading: 'Education & Credentials',
        items: [
          'MBBS – Deccan College of Medical Sciences, Dr. NTR University of Health Sciences (2008)',
          'MD (Internal Medicine) – Kasturba Medical College, Manipal (2015–2018)',
          'DM (Gastroenterology) – Amrita Institute of Medical Sciences (2019–2022)',
          'Clinical Observership in Dermatology – Singapore General Hospital (2014)',
        ],
      },
      {
        type: 'heading',
        icon: '🏥',
        heading: 'Conditions Commonly Managed',
        items: [
          'GERD (acid reflux), Gastritis, Peptic Ulcer Disease',
          'Irritable Bowel Syndrome (IBS)',
          'Inflammatory Bowel Disease (IBD)',
          'Gallbladder-related symptoms, Pancreatitis',
          'Chronic Liver Disease, Hepatitis',
          'Digestive bleeding and Jaundice',
        ],
      },
      {
        type: 'heading',
        icon: '🔬',
        heading: 'When to See Dr. Tangirala',
        items: [
          'Acidity, heartburn, reflux, or chest burning',
          'Ongoing abdominal pain, bloating, nausea, or vomiting',
          'Constipation or diarrhea lasting more than a few days',
          'Blood in stool, black stools, or unexplained weight loss',
          'Jaundice, abnormal liver tests, or suspected fatty liver disease',
        ],
      },
    ],
  },
  {
    id: 7,
    slug: 'gastroenterologist-in-asansol-dr-p-kranthi-kumar',
    image: '/d6.jpeg',
    name: 'Dr. P. Kranthi Kumar',
    qualification: 'MBBS, MD (General Medicine), DM (Gastroenterology)',
    specialty: 'Consultant Gastroenterologist',
    tagline: 'Trusted Gastro Care Comes to Asansol',
    phone: '7364921002 / 9134819976',
    email: 'acharjeehealth.in@gmail.com',
    location: '62 N S.B Gorai Road, Ismile More, Asansol, West Bengal',
    accent: '#fff3e0',
    accentBorder: '#fb8c00',
    badge: 'Gastro',
    title: 'Trusted Gastro Care Comes to Asansol: Dr. P. Kranthi Kumar Now Available at Acharjee Health Clinic',
    content: [
      {
        type: 'para',
        text: 'Good health begins with a healthy stomach. Acharjee Health Clinic & Pharmacy, Asansol, proudly announces the availability of Dr. P. Kranthi Kumar, one of the leading Gastroenterologists from Malla Reddy Narayana Multispeciality Hospital, Hyderabad.',
      },
      {
        type: 'heading',
        icon: '🎓',
        heading: 'Academic & Clinical Credentials',
        items: [
          'MBBS – Foundation in General Medicine',
          'MD (General Medicine) – Advanced Internal Medicine training',
          'DM (Gastroenterology) – Super-speciality degree in digestive health',
          'Currently associated with Malla Reddy Narayana Hospital, Hyderabad',
        ],
      },
      {
        type: 'heading',
        icon: '🏥',
        heading: 'Digestive Problems We Treat',
        items: [
          'Chronic Acidity & Gas',
          'Stomach Pain and Bloating',
          'Liver Disorders (Fatty Liver, Hepatitis)',
          'IBS (Irritable Bowel Syndrome)',
          'Constipation & Diarrhea',
          'Gastritis & Ulcers',
          'Pancreatic Disorders',
          'GERD / Acid Reflux',
          'Digestive issues due to lifestyle & stress',
        ],
      },
      {
        type: 'highlight',
        text: '📞 Please call +91 7364-921002 for Immediate Appointment Confirmation. Address: 62 N.S.B. Gorai Road, Opp. IMA House, Ismile More, Asansol. Hours: 9 am till 10 pm.',
      },
      {
        type: 'heading',
        icon: '✅',
        heading: 'Why Choose Acharjee Health Clinic?',
        items: [
          'Consultation with top specialists from reputed hospitals',
          'Clean, patient-friendly clinic environment',
          'Easy appointment process',
          'Affordable and transparent healthcare',
          'Trusted by hundreds of local families',
        ],
      },
    ],
    hasCommentForm: true,
  },
  {
    id: 8,
    slug: 'best-neurologist-in-asansol',
    image: '/d7.jpg',
    name: 'Dr. Sanjeev Kr. Suman',
    qualification: 'MBBS, MS (General Surgery), M.Ch (Neurosurgery)',
    specialty: 'Neurosurgeon & Neurologist',
    tagline: 'Top Neurologist Consultant in Asansol',
    phone: '+91 7364921002',
    email: 'acharjeehealth.in@gmail.com',
    location: 'Acharjee Health Clinic, Asansol, West Bengal',
    accent: '#ede7f6',
    accentBorder: '#7b1fa2',
    badge: 'Neuro',
    title: 'Meet our Best Neurologist in Asansol – Dr. Sanjeev Kumar Suman',
    content: [
      {
        type: 'para',
        text: 'Dr. Sanjeev Kumar Suman is one of the most promising and skilled neurosurgeons and neurologists in Asansol, practicing at the reputed Acharjee Health Clinic. A qualified M.Ch. Neurosurgeon from the prestigious Bangur Institute of Neurosciences, IPGME&R & SSKM Hospital, Kolkata, Dr. Suman brings cutting-edge neurosurgical advancements to Asansol.',
      },
      {
        type: 'heading',
        icon: '🎓',
        heading: 'Educational Background',
        items: [
          'MBBS – Vilasrao Deshmukh Government Medical College, Latur, Maharashtra',
          'MS (General Surgery) – VSSIMSAR, Burla, Odisha',
          'M.Ch. (Neurosurgery) – Bangur Institute of Neurosciences, IPGME&R & SSKM Hospital, Kolkata',
        ],
      },
      {
        type: 'heading',
        icon: '💼',
        heading: 'Professional Experience',
        items: [
          'Neurosurgery Resident – IPGME&R & SSKM Hospital, Kolkata (May 2022 – May 2025)',
          'Performed and assisted in high-end neuro and spine surgeries',
          'Managed complex cases including brain tumors, spinal deformities, neurotrauma',
          'Resident Doctor (General Surgery) – VSSIMSAR, Burla (Jun 2017 – Jun 2020)',
          'Executed 100+ surgical procedures with precision',
        ],
      },
      {
        type: 'heading',
        icon: '🔬',
        heading: 'Areas of Expertise',
        items: [
          'Brain and Spine Surgery', 'Stroke, Seizure & Epilepsy Management',
          'Brain Tumor & Spinal Cord Lesion Surgery', 'Degenerative Spine & Disc Disease Treatment',
          'Traumatic Brain & Spinal Injury Care', 'Neurovascular & Aneurysm Surgery',
          'Peripheral Nerve & Micro-Neurosurgery', 'Pediatric Neurosurgery & Congenital Disorders',
          'Parkinson\'s Disease & Multiple Sclerosis Consultation',
          'Chronic Headache & Migraine Treatment', 'Minimally Invasive Spine & Skull Base Surgery',
        ],
      },
      {
        type: 'heading',
        icon: '✅',
        heading: 'Why Patients Choose Dr. Sanjeev Kumar Suman',
        items: [
          'Advanced expertise in brain and spine surgery',
          'Evidence-based treatment with modern neuro techniques',
          'Compassionate, patient-first care philosophy',
          'Strong interdisciplinary coordination',
          'High patient trust and successful treatment outcomes',
        ],
      },
    ],
  },
  {
    id: 9,
    slug: 'dr-rituparna-mukherjee-mbbs-nilratan-sirkar-medical-college-hospital-kolkata',
    image: '/d8.png',
    name: 'Dr. Rituparna Mukherjee',
    qualification: 'MBBS, MS (ENT) – West Bengal University of Health Sciences',
    specialty: 'ENT & Head–Neck Surgeon',
    tagline: 'ENT & Head–Neck Surgeon | NRS Medical College, Kolkata',
    phone: '07364921002 / 7029386969',
    email: 'acharjeehealth.in@gmail.com',
    location: '62 N, S.B. Gorai Road, Opp. IMA House, Ismile, More, Asansol',
    accent: '#e3f2fd',
    accentBorder: '#1565c0',
    badge: 'ENT',
    title: 'Dr. Rituparna Mukherjee: ENT & Head–Neck Surgeon',
    content: [
      {
        type: 'para',
        text: 'Dr. Rituparna Mukherjee is a qualified ENT specialist holding MBBS and MS (ENT) from the West Bengal University of Health Sciences, with academic training at NRS Medical College. Focused on patient safety, minimally invasive techniques, and optimal recovery outcomes, Dr. Mukherjee ensures a seamless and reassuring treatment experience.',
      },
      {
        type: 'heading',
        icon: '🏥',
        heading: 'ENT Clinical Care',
        items: [
          'Diagnosis and treatment of ear, nose, and throat disorders',
          'Management of sinusitis, hearing loss, throat infections, allergies',
          'Voice and swallowing disorder evaluation',
          'ENT emergency care',
          'Post-operative follow-up and recovery management',
        ],
      },
      {
        type: 'heading',
        icon: '🔬',
        heading: 'Surgical Services',
        items: [
          'Microscopic and endoscopic ear surgeries',
          'Endoscopic sinus surgery',
          'Advanced throat procedures',
          'Thyroid, parotid, and salivary gland surgeries',
        ],
      },
      {
        type: 'heading',
        icon: '⚡',
        heading: 'Advanced Procedures',
        items: [
          'Skull base surgery (assistance)',
          'Neck dissection',
          'Oral cancer surgery with flap reconstruction',
          'Maxillectomy',
        ],
      },
      {
        type: 'heading',
        icon: '✅',
        heading: 'Why Choose Dr. Rituparna Mukherjee?',
        items: [
          'Patient-centric, result-oriented treatment approach',
          'Expertise in both medical and surgical ENT care',
          'Use of modern, minimally invasive techniques',
          'Focus on fast recovery and long-term outcomes',
          'Ethical, transparent, and personalized care',
        ],
      },
    ],
  },
  {
    id: 10,
    slug: 'top-urologist-in-asansol-kolkata',
    image: '/d9.png',
    name: 'Dr. K. Seshu Mohan',
    qualification: 'MCh (Urology), Fellowship in Minimally Invasive & Robotic Urology',
    specialty: 'Urologist & Kidney Transplant Surgeon',
    tagline: 'Best Urologist Dr. K.Seshu in Asansol, West Bengal | Acharjee Health',
    phone: '07364921002 / 7029386969',
    email: 'acharjeehealth.in@gmail.com',
    location: 'ACHARJEE PHARMACY, MORE C/O, 256/2, SB Gorai Rd, Ismile, Islampur, Hamid Nagar, Asansol, West Bengal 713301',
    accent: '#e0f2f1',
    accentBorder: '#00796b',
    badge: 'Urology',
    title: 'Meet our Top Urologist – Dr. K. Seshu Mohan',
    content: [
      {
        type: 'para',
        text: 'Dr. K. Seshu Mohan is a highly skilled urologist and kidney transplant surgeon known for treating complex urological and kidney conditions. His work in kidney transplants at Acharjee Healthcare and Pharmacy significantly improves the lives of patients with severe kidney and urinary tract diseases.',
      },
      {
        type: 'heading',
        icon: '🏆',
        heading: 'Advanced Training & Recognitions',
        items: [
          'Board-certified urologist with specialized training in kidney transplantation',
          'Fellowship in minimally invasive and robotic urology',
          'Awarded the Dr. C. Palanivelu Gold Medal for excellence in urological surgery',
          'Practices at Malla Reddy Hospital, Hyderabad',
        ],
      },
      {
        type: 'heading',
        icon: '🔬',
        heading: 'Comprehensive Urological Services',
        items: [
          'Kidney Transplantation – Complex surgery with post-transplant care',
          'Kidney Stone Management – Minimally invasive procedures',
          'Prostate Enlargement & Urinary Tract Infections',
          'Laparoscopic and Robotic Surgery',
          'Urological disorder diagnosis and treatment',
          'Personalized treatment plans and counselling',
        ],
      },
      {
        type: 'heading',
        icon: '⭐',
        heading: 'Patient Reviews',
        reviews: [
          { author: 'Laksh Niku', text: '"Sir is a very good doctor. I have done my son\'s kidney surgery and got very good results."' },
          { author: 'Sourav Bhaya', text: '"The best urologist and very helpful person. Does what you need for a patient. The best kidney transplant surgeon."' },
          { author: 'Nirmal Thakur', text: '"Good behavior and gentle."' },
        ],
      },
    ],
  },
  {
    id: 11,
    slug: 'cardiologists-in-asansol-kolkata',
    image: '/d10.png',
    name: 'Dr. Pradip Sarkar',
    qualification: 'MBBS, MD (Medicine), DM (Cardiology)',
    specialty: 'Cardiologist',
    tagline: 'Best Cardiologist in Asansol, West Bengal | Acharjee Health',
    phone: '07364921002 / 7029386969',
    email: 'acharjeehealth.in@gmail.com',
    location: 'Ismile More, ACHARJEE PHARMACY, C/O, SB Gorai Rd, Ismile, Islampur, Hamid Nagar, Asansol, West Bengal 713301',
    accent: '#f1f8e9',
    accentBorder: '#558b2f',
    badge: 'Cardio',
    title: 'About your Expert Cardiology Specialist – Meet Dr. Pradip Sarkar',
    content: [
      {
        type: 'para',
        text: 'With a profound commitment to patient-centric treatment, advanced interventional techniques, and preventive cardiology, Dr. Sarkar is a beacon of trust and expertise in Asansol, West Bengal.',
      },
      {
        type: 'heading',
        icon: '🎓',
        heading: 'Educational Background',
        items: [
          'MBBS – Calcutta National Medical College, University of Calcutta',
          'MD (Medicine) – Medical College, Kolkata (Asia\'s oldest medical institution)',
          'DM (Cardiology) – IPGME&R and SSKM Hospital (PG Hospital), Kolkata',
        ],
      },
      {
        type: 'heading',
        icon: '❤️',
        heading: 'Interventional Cardiology Services',
        items: [
          'Pacemaker & ICD implantation – CRT-D, CRT-P devices',
          'Coronary, renal, and peripheral angioplasty',
          'Device closure for congenital defects – ASD, PDA, heart vascular problems',
          'Balloon valvuloplasty – Minimally invasive valve procedures',
        ],
      },
      {
        type: 'heading',
        icon: '🔬',
        heading: 'Diagnostic Cardiology',
        items: [
          'Advanced imaging – Echocardiography, stress echocardiography, TMT',
          'Transesophageal echocardiography, Holter monitoring',
          'Head-up tilt table tests, ambulatory BP monitoring',
        ],
      },
      {
        type: 'heading',
        icon: '⭐',
        heading: 'Patient Reviews',
        reviews: [
          { author: 'Manoj Thakur', text: '"It\'s very happy to know Dr Pradip Sarkar, DM Cardiologist is now available at Asansol. The doctor is extremely polite and enthusiastic, listens to all your complaints so patiently and tends to it with so much compassion. One of the best cardiologists in Asansol. Highly recommended."' },
          { author: 'Khushi A5s', text: '"Best cardiologist doctor in Asansol."' },
          { author: 'Real Rider Mohit', text: '"Best cardiologist at Asansol, experienced doctors."' },
        ],
      },
    ],
  },
  {
    id: 12,
    slug: 'top-gynaecologist-in-asansol-kolkata',
    image: '/d11.png',
    name: 'Dr. Aishwarya Bhattacharya',
    qualification: 'MBBS, MD (Obstetrics & Gynaecology)',
    specialty: 'Gynaecologist & Obstetrician',
    tagline: 'Best Gynaec Dr. Aishwarya Bhattacharya in Asansol, West Bengal | Acharjee Health',
    phone: '07364921002 / 7029386969',
    email: 'acharjeehealth.in@gmail.com',
    location: 'ACHARJEE PHARMACY, MORE C/O, 256/2, SB Gorai Rd, Ismile, Islampur, Hamid Nagar, Asansol, West Bengal 713301',
    accent: '#fce4ec',
    accentBorder: '#d81b60',
    badge: 'Gynae',
    title: 'About Dr. Aishwarya Bhattacharya – Our Best Gynecologist and Obstetrician',
    content: [
      {
        type: 'para',
        text: 'Dr. Aishwarya Bhattacharya is committed to providing comprehensive, compassionate, and personalized healthcare for women at every stage of life. She is a board-certified gynecologist with over 8 years of experience in women\'s health, known for offering exceptional care in a warm and respectful environment.',
      },
      {
        type: 'heading',
        icon: '🔬',
        heading: 'Area of Expertise',
        items: [
          'Preventive care (annual exams, pap smears)',
          'Prenatal care and pregnancy management',
          'Contraception and family planning counselling',
          'Treatment for menstrual issues and hormonal imbalances',
          'Managing infections and sexually transmitted diseases (STDs)',
          'Surgical procedures (laparoscopy, hysterectomy)',
          'Post-menopausal care',
        ],
      },
      {
        type: 'heading',
        icon: '🏥',
        heading: 'Comprehensive Services',
        items: [
          'Routine Gynecological Exams – Annual check-ups, pap smears, breast exams',
          'Prenatal and Postpartum Care – Complete care throughout pregnancy',
          'Contraception & Family Planning – Personalized advice',
          'Menstrual Health & Disorders – Irregular periods, heavy bleeding',
          'Fertility Support – Guidance for challenges with conception',
          'Menopause & Hormonal Therapy – Including HRT options',
          'Surgical Care – Minimally invasive laparoscopy and hysterectomy',
        ],
      },
      {
        type: 'heading',
        icon: '⭐',
        heading: 'Patient Reviews',
        reviews: [
          { author: 'Santu Pradhan', text: '"Dr Aishwarya made me feel at ease during my appointment and explained everything thoroughly. I trust her completely with my health."' },
          { author: 'Sheema', text: '"I highly recommend Dr Aishwarya. She is thorough, caring, and made me feel comfortable with my treatment plan."' },
        ],
      },
    ],
  },
  {
    id: 13,
    slug: 'top-pediatrician-in-asansol-kolkata',
    image: '/d12.png',
    name: 'Dr. Nibedita Kabiraj',
    qualification: 'MBBS, MD (Pediatrics)',
    specialty: 'Child Specialist & Pediatrician',
    tagline: 'Dr. Nibedita Kabiraj, Best Pediatrician in Asansol, West Bengal | Acharjee Health',
    phone: '+91 73649 21002 / +91 70293 86969',
    email: 'acharjeehealth.in@gmail.com',
    location: 'ACHARJEE PHARMACY, MORE C/O, 256/2, SB Gorai Rd, Ismile, Islampur, Hamid Nagar, Asansol, West Bengal 713301',
    accent: '#f1f8e9',
    accentBorder: '#388e3c',
    badge: 'Paeds',
    title: 'Meet our Top Pediatrician & Child Specialist – Dr. Nibedita Kabiraj',
    experience: '11+ Years',
    content: [
      {
        type: 'para',
        text: 'Dr. Nibedita Kabiraj is a seasoned pediatrician based in Asansol, West Bengal, with MBBS and MD specializing in Pediatrics. With more than 11 years of experience, she has been working at Sharanya and Kisholoy Children\'s Hospital in Burdwan. She is an expert in neonatology, successfully treating premature babies as light as 720 grams born at only 24 weeks.',
      },
      {
        type: 'heading',
        icon: '🔬',
        heading: 'Critical Newborn Conditions Treated',
        items: [
          'Meconium Aspiration Syndrome',
          'Birth Asphyxia',
          'Neonatal Seizures',
          'Pneumothorax',
          'Other complex newborn complications with proper follow-up care',
        ],
      },
      {
        type: 'heading',
        icon: '🏥',
        heading: 'Specialized Pediatric & Neonatal Care Services',
        items: [
          'Advanced NICU technology – Management of premature and high-risk newborns',
          'Neonatal ventilation, central line placement, surfactant administration',
          'Exchange transfusion and chest drain procedures',
          'All childhood vaccinations for total immunization',
          'Growth and development evaluation',
          'Evidence-based management of prevalent pediatric conditions',
        ],
      },
      {
        type: 'heading',
        icon: '⭐',
        heading: 'Patient Reviews',
        reviews: [
          { author: 'Mukul Kumar', text: '"She is the best of all the doctors (Paediatricians) at Asansol-Durgapur I have ever seen. She puts a hundred percent effort into treating children and has a good sense of diagnosis. My daughter is a premature baby admitted to NICU, but thanks to Dr. Nibedita Kabiraj, who cured her."' },
          { author: 'Hariji Prasad', text: '"She is among the best pediatricians/child specialists I have seen in Asansol. What I like most is that she cares about her patients. Thank you, Dr. Nibedita Kabiraj."' },
          { author: 'Arnab Das', text: '"My experience is excellent with this doctor — one of the kindest pediatricians. Every time we consulted, we got proper treatment and guidance."' },
        ],
      },
    ],
  },
  {
    id: 14,
    slug: 'best-orthopaedic-knee-replacement-surgeon-in-asansol-dr-ratnakar-rao-dr-ratnakar-rao',
    image: '/d13.png',
    name: 'Dr. Ratnakar Rao K',
    qualification: 'MBBS, MS (Orthopedics), AMC AR Fellowship, NUHS (Singapore)',
    specialty: 'Chief Consultant Orthopaedic & Joint Replacement Surgeon',
    tagline: 'Best Orthopaedic and Knee Replacement Surgeon in Asansol | Dr. Ratnakar Rao K',
    phone: '07364921002 / 7029386969',
    email: 'acharjeehealth.in@gmail.com',
    location: '62 N, S.B. Gorai Road, Opp. IMA House, Ismile, More, Asansol',
    accent: '#e3f2fd',
    accentBorder: '#1976d2',
    badge: 'Ortho',
    title: 'Best Orthopaedic & Knee Replacement Surgeon in Asansol | Dr. Ratnakar Rao K',
    experience: '24+ Years',
    procedures: '1000+',
    content: [
      {
        type: 'para',
        text: 'Dr. Ratnakar Rao K is one of India\'s leading Orthopaedic and Joint Replacement Surgeons, with over 24 years of experience in advanced orthopedic care, robotic joint replacement, sports injury treatment, and trauma management. Currently serving as Senior Consultant Orthopaedic & Joint Replacement Surgeon at Apollo Hospitals, Hyderabad, he has successfully performed more than 1,000 orthopedic and joint replacement procedures.',
      },
      {
        type: 'heading',
        icon: '🔬',
        heading: 'Specializations',
        items: [
          'Robotic Total Knee Replacement Surgery',
          'Robotic Total Hip Replacement Surgery',
          'Knee Arthritis Treatment',
          'Sports Injury Management',
          'ACL Reconstruction Surgery',
          'Arthroscopic Knee & Shoulder Surgery',
          'Trauma & Fracture Care',
          'Shoulder Pain Treatment',
          'Joint Preservation Procedures',
          'Orthopaedic Second Opinion Consultations',
        ],
      },
      {
        type: 'heading',
        icon: '✅',
        heading: 'Why Choose Dr. Ratnakar Rao?',
        items: [
          '24+ years of orthopedic expertise',
          '1,000+ successful orthopedic and joint replacement procedures',
          'International training from Singapore, Australia, Germany, and India',
          'Advanced robotic joint replacement techniques',
          'Evidence-based treatment approach',
          'Personalized patient care and rehabilitation guidance',
        ],
      },
    ],
  },
  {
    id: 15,
    slug: 'dr-riya-sinha-ent-head-and-neck-surgeon-mbbs-ms-ent-head-and-neck-surgery',
    image: '/d14.png',
    name: 'Dr. Riya Sinha',
    qualification: 'MBBS, MS (ENT & Head and Neck Surgery)',
    specialty: 'ENT & Head Neck Surgeon',
    tagline: 'ENT & Head and Neck Surgeon | MBBS, MS (ENT & Head and Neck Surgery)',
    phone: '07364921002 / 7029386969',
    email: 'acharjeehealth.in@gmail.com',
    location: '62 N, S.B. Gorai Road, Opp. IMA House, Ismile, More, Asansol',
    accent: '#e8eaf6',
    accentBorder: '#3949ab',
    badge: 'ENT',
    title: 'Dr. Riya Sinha – ENT & Head and Neck Surgeon',
    content: [
      {
        type: 'para',
        text: 'Dr. Riya Sinha is a qualified ENT & Head and Neck Surgeon with MBBS and MS (ENT & Head and Neck Surgery). She is dedicated to providing expert, evidence-based care for all ear, nose, throat, and head-neck conditions at Acharjee Health Clinic, Asansol.',
      },
      {
        type: 'heading',
        icon: '🏥',
        heading: 'ENT Clinical Care',
        items: [
          'Diagnosis and treatment of ear, nose, and throat disorders',
          'Management of sinusitis, hearing loss, throat infections, and allergies',
          'Voice and swallowing disorder evaluation',
          'ENT emergency care and post-operative follow-up',
        ],
      },
      {
        type: 'heading',
        icon: '🔬',
        heading: 'Surgical Services',
        items: [
          'Microscopic and endoscopic ear surgeries',
          'Endoscopic sinus surgery (FESS)',
          'Advanced throat procedures',
          'Thyroid, parotid, and salivary gland surgeries',
          'Skull base surgery and neck dissection',
        ],
      },
      {
        type: 'heading',
        icon: '✅',
        heading: 'Why Choose Dr. Riya Sinha?',
        items: [
          'Patient-centric, result-oriented treatment approach',
          'Use of modern, minimally invasive techniques',
          'Focus on fast recovery and long-term outcomes',
          'Ethical, transparent, and personalized care',
        ],
      },
    ],
  },
];

export function getDoctorBySlug(slug: string): DoctorDetail | undefined {
  return doctorsData.find(d => d.slug === slug);
}
